# Telegram Bot Token
BOT_TOKEN = 'YOUR_BOT_TOKEN'

# Google OAuth2 credentials
GOOGLE_CLIENT_ID = 'YOUR_CLIENT_ID'
GOOGLE_CLIENT_SECRET = 'YOUR_CLIENT_SECRET'
GOOGLE_REDIRECT_URI = 'YOUR_REDIRECT_URI'
